### ISSUE TITLE
Konfigurowanie ilości slotów

### ISSUE THREAD

**Issue by Feerko** [kacperduras/FunnyTab#3]
Cześć, pomyśl nad dodaniem zmiennej dla ilości slotów w tabie.

**Comment by kacperduras** [comment]
@Feerko cześć, sorki że tak musiałeś długo czekać. Już leci do TODO.

**Comment by kacperduras** [comment]
@Feerko tak sobie teraz o tym issue przypomniałem i zastanawiam się, o co Ci w nim chodzi? Wytłumacz jaśniej, bo nie rozumiem.

**Comment by xSzescianPL** [comment]
Mu chodzi o to żeby była szersza tablista :P

**Comment by xSzescianPL** [comment]
Czyli że np. można było zrobić TabListe która ma 4 rzędy nawet jak jest 1 gracz :P

**Comment by kacperduras** [comment]
Ale tak właśnie jest @xSzescianPL. Tab lista ma domyślnie 4 rzędy.

**Comment by Feerko** [comment]
Domyślnie ma 4 rzędy a przydałoby się, żeby była możliwość ustawienia 3 rzędów w configu.

**Comment by kacperduras** [comment]
No to nie slotów, tylko kolumn. Mało precyzyjnie się wyrażasz.
