### ISSUE TITLE
Zmiana całej tablisty.

### ISSUE THREAD

**Issue by xdpg66** [kacperduras/FunnyTab#6]
Cześć, zmieniłem trochę tablistę, itd... I gdy odpalam plugin z moim plikiem konfiguracyjnym ciągle mam tą domyślną. Nawet gdy {GTOP-1} zamieniłem na TEST również przywracało domyślną wersję.

**Comment by kacperduras** [comment]
Może jakieś konkrety apropo specyfikacji serwera? Kryształowej kuli nie posiadam @xdpg66

**Comment by xdpg66** [comment]
PaperSpigot, wersja 1.8 coś jeszcze?

**Comment by kacperduras** [comment]
@xdpg66 a build? Przecież z cyklu wersji 1.8 jest ich kilka.
